### ISSUE TITLE
Performance ideas

### ISSUE THREAD

**Issue by dlasher** [Xefrok/BitBruteForce-Wallet#12]
So the primary throttle is searching the bits.txt file. Use a much larger file, and the rate drops very low.

Might I suggest each CPU thread writes to a DB (mongo?), then other threads can search for matches and delete when no match is found?

**Comment by cabanu** [comment]
Use mine :-)
I updated it. It's works with MySQL
https://github.com/cabanu/BitBruteForce-Wallet

371 K/s/Core - Used settings = 6 Cores - 6 * 371 * 60 * 60 * 24 = 192.326.400 addresses / day = 70.199.136.000 addresses / year

**Comment by kubi34** [comment]
> Benimkini kullan :-)
> Onu güncelledim. MySQL https://github.com/cabanu/BitBruteForce-Wallet ile çalışır
> [](https://github.com/cabanu/BitBruteForce-Wallet)
> 
> 371 K / s / Çekirdek - Kullanılan ayarlar = 6 Çekirdek - 6 * 371 * 60 * 60 * 24 = 192.326.400 adres / gün = 70.199.136.000 adres / yıl

Hey I cant run.
This is the error.
(base) C:\Users\kubil\Downloads\BitBruteForce-Wallet-master (1)\BitBruteForce-Wallet-master>generator.py
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\mysql\connector\connection_cext.py", line 233, in _open_connection
    self._cmysql.connect(**cnx_kwargs)
_mysql_connector.MySQLInterfaceError: Access denied for user 'DBUSER'@'localhost' (using password: YES)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\kubil\Downloads\BitBruteForce-Wallet-master (1)\BitBruteForce-Wallet-master\generator.py", line 22, in <module>
    mydb = mysql.connector.connect(
  File "C:\ProgramData\Anaconda3\lib\site-packages\mysql\connector\__init__.py", line 277, in connect
    return CMySQLConnection(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\mysql\connector\connection_cext.py", line 86, in __init__
    self.connect(**kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\mysql\connector\abstracts.py", line 1003, in connect
    self._open_connection()
  File "C:\ProgramData\Anaconda3\lib\site-packages\mysql\connector\connection_cext.py", line 235, in _open_connection
    raise errors.get_mysql_exception(msg=exc.msg, errno=exc.errno,
mysql.connector.errors.ProgrammingError: 1045 (28000): Access denied for user 'DBUSER'@'localhost' (using password: YES)

**Comment by kubi34** [comment]
> Benimkini kullan :-)
> Onu güncelledim. MySQL https://github.com/cabanu/BitBruteForce-Wallet ile çalışır
> [](https://github.com/cabanu/BitBruteForce-Wallet)
> 
> 371 K / s / Çekirdek - Kullanılan ayarlar = 6 Çekirdek - 6 * 371 * 60 * 60 * 24 = 192.326.400 adres / gün = 70.199.136.000 adres / yıl

And I do not understand how this application works. Should we add hundreds of wallet addresses manually to the wallet.txt file.

How will we know if this application finds us the right key Where is it recording

**Comment by kubi34** [comment]
> Use mine :-)
> I updated it. It's works with MySQL
> https://github.com/cabanu/BitBruteForce-Wallet
> 
> 371 K/s/Core - Used settings = 6 Cores - 6 * 371 * 60 * 60 * 24 = 192.326.400 addresses / day = 70.199.136.000 addresses / year
4 hours working  and still NULL 
is it normal?
And my processor is i7 6700 HQ  what is core value for optimum
![image](https://user-images.githubusercontent.com/54383069/108612620-65fd0b80-73fb-11eb-8a4b-68eb5428aad0.png)

**Comment by cabanu** [comment]
You have to fill you're DB with all the addresses you want to check. This script uses the UPDATE query for all generated addresses. When an address exist => it will put the secret key in the DB. If the generated address is not present in your DB: nothing happens.

**Comment by kubi34** [comment]
> You have to fill you're DB with all the addresses you want to check. This script uses the UPDATE query for all generated addresses. When an address exist => it will put the secret key in the DB. If the generated address is not present in your DB: nothing happens.

I added more than 60 million wallet addresses to the first column in the database. There is a text file reading process at the bottom of the software you developed. So what are we going to use this text file for?
![image](https://user-images.githubusercontent.com/54383069/108905473-cf199480-7630-11eb-8e7c-49cbd6cf52c1.png)

**Comment by kubi34** [comment]
> You have to fill you're DB with all the addresses you want to check. This script uses the UPDATE query for all generated addresses. When an address exist => it will put the secret key in the DB. If the generated address is not present in your DB: nothing happens.

Hi
Waiting for answer

**Comment by jomagalo** [comment]
@cabanu My program modification with set() gives me 540K/s * core on a raspi.

540 K/s * Core - Used settings = 4 Cores - 4 * 540 * 60 * 60 * 24 = 186.624.000 addresses / day = 68.117.760.000 addresses / year
